[schema]
enabled = true

[[schema.associations]]
glob    = "**/easywall.toml"
url     = "https://jp1337.github.io/easywall/schemas/easywall.schema.json"

[[schema.associations]]
glob    = "**/web.toml"
url     = "https://jp1337.github.io/easywall/schemas/web.schema.json"
