[schema]
enabled = true

[[schema.associations]]
glob    = "**/easywall.toml"
url     = "https://easywall-project.org/schemas/easywall.schema.json"

[[schema.associations]]
glob    = "**/web.toml"
url     = "https://easywall-project.org/schemas/web.schema.json"
