[supervisord]
nodaemon=true
logfile=/var/log/easywall/supervisord.log
pidfile=/run/easywall/supervisord.pid

[program:easywall-core]
command=/usr/sbin/easywall-core --config /etc/easywall/easywall.toml
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:easywall-web]
command=/usr/sbin/easywall-web --config /etc/easywall/web.toml
directory=/usr/share/easywall
autostart=true
autorestart=true
priority=20
startsecs=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
