package core

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/nftables"
	"github.com/jp1337/easywall/internal/shared"
)

var updateForwardGolden = flag.Bool("update-forward-golden", false,
	"rewrite testdata/forward_v4_golden.txt from the current buildForwardChain")

// renderForward is every rule's expressions and userdata, one line each: the
// whole of what reaches the kernel from buildForwardChain. One expression at a
// time: fmt expands a pointer to a struct only at depth 0, so `%#v` of the
// []expr.Any would print addresses and differ on every run (plan review #1).
// None of the expressions the forward chain builds holds a nested pointer.
func renderForward(rules []*nftables.Rule) string {
	var b strings.Builder
	for _, r := range rules {
		for _, e := range r.Exprs {
			fmt.Fprintf(&b, "%#v; ", e)
		}
		fmt.Fprintf(&b, "| %x\n", r.UserData)
	}
	return b.String()
}

// forwardGoldenMatrix is every IPv4-only shape the forward chain can take,
// with the rule shapes that touch families: no sources, an IPv4 source, an
// IPv6 source, a range, UDP, and a host-only rule that must not appear.
func forwardGoldenMatrix(t *testing.T) string {
	t.Helper()
	rules := shared.Rules{
		TCP: []shared.PortRule{
			{ID: "aaaaaaaaaaa1", Port: "25", Scope: shared.ScopeForwarded},
			{ID: "aaaaaaaaaaa2", Port: "443", Scope: shared.ScopeForwarded, Sources: []string{"203.0.113.0/24"}},
			{ID: "aaaaaaaaaaa3", Port: "587", Scope: shared.ScopeForwarded, Sources: []string{"2001:db8::/32"}},
			{ID: "aaaaaaaaaaa4", Port: "22", Scope: shared.ScopeHost},
		},
		UDP: []shared.PortRule{
			{ID: "aaaaaaaaaaa5", Port: "8000:9000", Scope: shared.ScopeBoth},
		},
	}
	var out strings.Builder
	for _, d := range []struct {
		name   string
		docker shared.DockerConfig
	}{{"filtered", filteredDocker()}, {"open", openDocker()}} {
		for _, r := range []shared.RoutingConfig{
			{Mode: shared.RoutingClosed},
			{Mode: shared.RoutingNetworks, Networks: []string{"10.9.0.0/16"}},
			{Mode: shared.RoutingOpen},
		} {
			for _, cidrs := range [][]string{{"172.17.0.0/16", "172.18.0.0/16"}, nil} {
				fmt.Fprintf(&out, "== %s routing=%s cidrs=%v\n", d.name, r.Mode, cidrs)
				out.WriteString(renderForward(buildForward(t, d.docker, r, rules, cidrs)))
			}
		}
	}
	return out.String()
}

// D2: an IPv4-only host's forward chain is byte-identical to 2.23.2's. The
// golden was captured on the pre-2.24 base (see the plan, Task 2 Step 1) and is
// never regenerated by 2.24's code.
func TestForwardChain_AnIPv4OnlyHostIsByteIdentical(t *testing.T) {
	path := filepath.Join("testdata", "forward_v4_golden.txt")
	got := forwardGoldenMatrix(t)
	if *updateForwardGolden {
		if err := os.WriteFile(path, []byte(got), 0o600); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path) // #nosec G304 -- a fixed path in this package
	if err != nil {
		t.Fatal(err)
	}
	if got != string(want) {
		t.Errorf("the forward chain of an IPv4-only host changed.\n--- want\n%s\n--- got\n%s", want, got)
	}
}
